# Generated by Django 2.2.5 on 2020-09-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendItApp', '0002_auto_20200903_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('Redpoint', 'Redpoint'), ('Flash', 'Flash'), ('Onsight', 'Onsight'), ('Blackpoint', 'Blackpoint'), ('Pinkpoint', 'Pinkpoint'), ('Flail', 'Flail'), ('ToDo', 'ToDo')], max_length=40),
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('Trad', 'Trad'), ('Alpine', 'Alpine'), ('Boulder', 'Boulder'), ('Sport', 'Sport'), ('Ice', 'Ice')], max_length=40),
        ),
    ]
