# Generated by Django 2.2.5 on 2020-09-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendItApp', '0003_auto_20200903_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('Blackpoint', 'Blackpoint'), ('ToDo', 'To Do'), ('Redpoint', 'Redpoint'), ('Flash', 'Flash'), ('Pinkpoint', 'Pinkpoint'), ('Onsight', 'Onsight'), ('Flail', 'Flail')], max_length=40),
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('Alpine', 'Alpine'), ('Ice', 'Ice'), ('Trad', 'Trad'), ('Boulder', 'Boulder'), ('Sport', 'Sport')], max_length=40),
        ),
    ]
