# Generated by Django 2.2.5 on 2020-09-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendItApp', '0004_auto_20200903_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('Blackpoint', 'Blackpoint'), ('Pinkpoint', 'Pinkpoint'), ('Onsight', 'Onsight'), ('Redpoint', 'Redpoint'), ('Flash', 'Flash'), ('ToDo', 'To Do'), ('Flail', 'Flail')], max_length=40),
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Alpine', 'Alpine'), ('Trad', 'Trad'), ('Boulder', 'Boulder'), ('Ice', 'Ice')], max_length=40),
        ),
    ]
