# Generated by Django 2.2.5 on 2020-09-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendItApp', '0005_auto_20200903_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('Pinkpoint', 'Pinkpoint'), ('Flail', 'Flail'), ('ToDo', 'To Do'), ('Redpoint', 'Redpoint'), ('Flash', 'Flash'), ('Blackpoint', 'Blackpoint'), ('Onsight', 'Onsight')], max_length=40),
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('Ice', 'Ice'), ('Sport', 'Sport'), ('Boulder', 'Boulder'), ('Alpine', 'Alpine'), ('Trad', 'Trad')], max_length=40),
        ),
    ]
