# Generated by Django 2.2.5 on 2020-09-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendItApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('Blackpoint', 'Blackpoint'), ('Pinkpoint', 'Pinkpoint'), ('Redpoint', 'Redpoint'), ('ToDo', 'ToDo'), ('Flail', 'Flail'), ('Flash', 'Flash'), ('Onsight', 'Onsight')], max_length=40),
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('Ice', 'Ice'), ('Trad', 'Trad'), ('Sport', 'Sport'), ('Alpine', 'Alpine'), ('Boulder', 'Boulder')], max_length=40),
        ),
    ]
