# Generated by Django 2.2.5 on 2020-09-04 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SendItApp', '0007_auto_20200903_1935'),
        ('SendItApp', '0008_auto_20200904_0026'),
    ]

    operations = [
    ]
