# Generated by Django 2.2.5 on 2020-09-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendItApp', '0009_merge_20200904_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('Redpoint', 'Redpoint'), ('Flail', 'Flail'), ('Onsight', 'Onsight'), ('ToDo', 'ToDo'), ('Flash', 'Flash'), ('Pinkpoint', 'Pinkpoint'), ('Blackpoint', 'Blackpoint')], max_length=40),
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('Alpine', 'Alpine'), ('Boulder', 'Boulder'), ('Ice', 'Ice'), ('Trad', 'Trad'), ('Sport', 'Sport')], max_length=40),
        ),
    ]
