# Generated by Django 2.2.5 on 2020-09-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendItApp', '0012_auto_20200904_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boulder',
            name='rock',
            field=models.CharField(choices=[('Granite', 'Granite'), ('Limestone', 'Limestone'), ('Quartzite', 'Quartzite'), ('Sandstone', 'Sandstone'), ('Unknown', 'Unknown')], default='Unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='boulder',
            name='status',
            field=models.CharField(choices=[('Flash', 'Flash'), ('In Progress', 'In Progress'), ('To Do', 'To Do')], default='Flash', max_length=40),
        ),
        migrations.AlterField(
            model_name='sport',
            name='rock',
            field=models.CharField(choices=[('Granite', 'Granite'), ('Limestone', 'Limestone'), ('Quartzite', 'Quartzite'), ('Sandstone', 'Sandstone'), ('Cobble', 'Cobble'), ('Unknown', 'Unknown')], default='Unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='sport',
            name='status',
            field=models.CharField(choices=[('Onsight', 'Onsight'), ('Redpoint', 'Redpoint'), ('Pinkpoint', 'Pinkpoint'), ('To Do', 'To Do'), ('Flash', 'Flash'), ('Flail', 'Flail')], default='To Do', max_length=40),
        ),
    ]
