# Generated by Django 2.2.5 on 2020-09-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SendItApp', '0018_attempt_shoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name_plural': ['shoes', 'status', 'notes']},
        ),
    ]
