# Generated by Django 2.2.5 on 2020-09-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SendItApp', '0019_auto_20200910_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['date'], 'verbose_name_plural': ['shoes', 'status', 'notes']},
        ),
    ]
