# Generated by Django 2.2.5 on 2020-09-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendItApp', '0021_auto_20200910_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='name',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Name'),
        ),
    ]
