# Generated by Django 2.2.5 on 2020-10-28 04:18

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('BookCatalogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('book_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='bk_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='bk_pub_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='book',
            name='bk_purchase_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='book',
            name='bk_series',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='bk_type',
            field=models.CharField(choices=[('hardback', 'hardback'), ('paperback', 'paperback'), ('kindle', 'kindle'), ('epub', 'epub'), ('pdf', 'pdf')], default='', max_length=15),
        ),
    ]
