# Generated by Django 2.2.5 on 2020-10-30 22:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('BookCatalogApp', '0002_auto_20201027_2118'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
    ]
