# Generated by Django 2.2.5 on 2020-11-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookCatalogApp', '0003_auto_20201030_1553'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
