# Generated by Django 2.2.5 on 2020-11-04 05:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('BookCatalogApp', '0004_auto_20201103_1807'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
    ]
