# Generated by Django 2.2.5 on 2020-11-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookCatalogApp', '0005_auto_20201103_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bk_type',
            field=models.CharField(choices=[('hardback', 'Hardback'), ('paperback', 'Paperback'), ('kindle', 'Kindle'), ('epub', 'Epub'), ('pdf', 'PDF')], default='', max_length=15),
        ),
    ]
