# Generated by Django 2.2.5 on 2020-11-05 23:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_title', models.CharField(max_length=50)),
                ('episode_season', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('episode_date', models.DateField()),
            ],
            managers=[
                ('Episodes', django.db.models.manager.Manager()),
            ],
        ),
    ]
