# Generated by Django 2.2.5 on 2020-09-23 02:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_happ_user',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nick_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('street_address', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            managers=[
                ('admin', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='hike_preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_types_of_hikes', models.CharField(choices=[('F', 'Flat'), ('H', 'Hilly'), ('M', 'Mountains'), ('R', 'Rivers'), ('G', 'Glacier'), ('L', 'Lake')], max_length=30)),
                ('perfect_length_of_hike', models.CharField(choices=[('1-2', '1-2 Miles'), ('2-5,', '2-5 Miles'), ('5-8', '5-8 Miles'), ('8-10', '8-10 Miles'), ('10+', '10+ Miles')], max_length=30)),
                ('avid_hiker', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('how_healthy_are_you', models.CharField(choices=[('PH', 'Not to Healthy'), ('SH', 'Somewhat Healthy'), ('H', 'Healthy'), ('PH', 'Pretty Healthy'), ('VH', 'Very Healthy')], max_length=30)),
                ('nick_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HikingApp.create_happ_user')),
            ],
            managers=[
                ('admin', django.db.models.manager.Manager()),
            ],
        ),
    ]
