# Generated by Django 2.2.5 on 2020-09-26 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HikingApp', '0002_auto_20200923_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike_preferences',
            name='nick_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HikingApp.create_happ_user'),
        ),
    ]
