# Generated by Django 2.2.5 on 2020-09-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FishKeepingApp', '0002_fishwishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishwishlist',
            name='image',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
