# Generated by Django 2.2.5 on 2020-09-12 21:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('FishKeepingApp', '0003_auto_20200912_1124'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fishwishlist',
            managers=[
                ('fish', django.db.models.manager.Manager()),
            ],
        ),
    ]
