# Generated by Django 2.2.5 on 2020-09-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FishKeepingApp', '0005_auto_20200914_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishwishlist',
            name='fish_type',
            field=models.CharField(choices=[('Freshwater', 'Freshwater'), ('Brackish', 'Brackish'), ('Saltwater', 'Saltwater')], max_length=2, null=True),
        ),
    ]
