# Generated by Django 2.2.5 on 2020-11-04 17:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Your Characters Name')),
                ('race', models.CharField(choices=[('Elf', 'Elf'), ('Half-Elf', 'Half-Elf'), ('Human', 'Human'), ('Half-orc', 'Half-orc'), ('Halfling', 'Halfling'), ('Dwarf', 'Dwarf')], max_length=50)),
                ('character_class', models.CharField(choices=[('Fighter', 'Fighter'), ('Wizard', 'Wizard'), ('Rouge', 'Rouge'), ('Ranger', 'Ranger'), ('Paladin', 'Paladin'), ('Druid', 'Druid')], max_length=50)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
