# Generated by Django 2.2.5 on 2020-10-12 23:44

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pokemon_Name', models.CharField(max_length=50)),
                ('Pokemon_Number', models.IntegerField(max_length=5)),
                ('Pokemon_notes', models.CharField(max_length=300)),
            ],
            managers=[
                ('Sightings', django.db.models.manager.Manager()),
            ],
        ),
    ]
