# Generated by Django 2.2.5 on 2020-10-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeDex', '0002_sighting_pokemon_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Pokemon_Number',
            field=models.IntegerField(),
        ),
    ]
