# Generated by Django 2.2.5 on 2020-10-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covidInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(default='', max_length=50)),
                ('last_Name', models.CharField(default='', max_length=50)),
                ('emailAddress', models.EmailField(max_length=50)),
                ('covid_Question', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
        ),
    ]
