# Generated by Django 2.2.5 on 2020-10-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidUpdateApp', '0002_auto_20201002_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='story_Questions',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
