# Generated by Django 2.2.5 on 2020-10-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidUpdateApp', '0003_contact_story_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='covid_Question',
            field=models.BooleanField(verbose_name='Have you been affected by Covid?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='story_Questions',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
