# Generated by Django 2.2.5 on 2020-10-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidUpdateApp', '0005_auto_20201002_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='covid_Question',
            field=models.BooleanField(verbose_name='Have you been affected by Covid?'),
        ),
    ]
