# Generated by Django 2.2.5 on 2020-10-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidUpdateApp', '0006_auto_20201002_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='covid_Question',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Have you been affected by Covid?'),
        ),
    ]
