# Generated by Django 2.2.5 on 2020-10-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CovidUpdateApp', '0007_auto_20201002_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emailAddress',
            new_name='email_Address',
        ),
    ]
