# Generated by Django 2.2.5 on 2020-10-06 07:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('CovidUpdateApp', '0009_auto_20201002_1641'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
