# Generated by Django 2.2.5 on 2020-10-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CovidUpdateApp', '0010_auto_20201006_0046'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
            ],
        ),
    ]
