# Generated by Django 2.2.5 on 2020-10-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidUpdateApp', '0011_auto_20201006_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='story_Questions',
            field=models.TextField(default='', max_length=1000, verbose_name='Tell us your Silver Lining Story'),
        ),
    ]
