# Generated by Django 2.2.5 on 2020-10-09 07:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('CovidUpdateApp', '0012_auto_20201006_0139'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
