# Generated by Django 2.2.5 on 2020-10-10 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CovidUpdateApp', '0013_auto_20201009_0050'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
            ],
        ),
    ]
