# Generated by Django 2.2.5 on 2020-10-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurfSpotsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotName', models.CharField(blank=True, default='', max_length=50, verbose_name='Surf Spot Name')),
                ('location', models.CharField(blank=True, default='', max_length=60, verbose_name='Location')),
                ('description', models.TextField(blank=True, default='', max_length=300, verbose_name='Your Description')),
                ('rating', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='Your Rating')),
            ],
        ),
        migrations.DeleteModel(
            name='SurfSpots',
        ),
    ]
