# Generated by Django 2.2.5 on 2020-10-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurfSpotsApp', '0002_auto_20201030_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='location',
            field=models.CharField(default='', max_length=80, verbose_name='County/State'),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Your Rating'),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='spotName',
            field=models.CharField(default='', max_length=50, verbose_name='Surf Spot Name'),
        ),
    ]
