# Generated by Django 2.2.5 on 2020-09-23 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='theBigOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishing_Name', models.CharField(blank=True, max_length=30)),
                ('fish_Type', models.CharField(blank=True, max_length=30)),
                ('fish_Length', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('fish_Weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('body_of_Water', models.CharField(blank=True, max_length=60)),
                ('tackle_Used', models.CharField(max_length=30)),
                ('boatOrBank', models.BooleanField(blank=True, choices=[(True, 'Boat'), (False, 'Bank')], null=True, verbose_name='Boat or Bank Fishing?')),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=30)),
                ('last_Name', models.CharField(max_length=30)),
                ('emailAddress', models.CharField(max_length=60)),
                ('fishing_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatchIdentificationApp.theBigOne')),
            ],
        ),
    ]
