# Generated by Django 2.2.5 on 2020-09-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatchIdentificationApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='TheContact',
        ),
        migrations.AlterField(
            model_name='thecontact',
            name='fishing_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatchIdentificationApp.TheBigOne'),
        ),
    ]
