# Generated by Django 2.2.5 on 2020-09-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatchIdentificationApp', '0002_auto_20200923_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thecontact',
            name='fishing_Name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
