# Generated by Django 2.2.5 on 2020-09-24 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatchIdentificationApp', '0003_auto_20200923_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thebigone',
            name='fishing_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatchIdentificationApp.TheContact'),
        ),
    ]
