# Generated by Django 2.2.5 on 2020-09-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatchIdentificationApp', '0004_auto_20200924_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thebigone',
            old_name='fishing_Name',
            new_name='user_Name',
        ),
        migrations.RenameField(
            model_name='thecontact',
            old_name='fishing_Name',
            new_name='user_Name',
        ),
    ]
