# Generated by Django 2.2.5 on 2020-09-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatchIdentificationApp', '0006_auto_20200924_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thecontact',
            name='emailAddress',
            field=models.EmailField(max_length=60),
        ),
    ]
