# Generated by Django 2.2.5 on 2020-09-30 19:04

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient1', models.CharField(max_length=30)),
                ('ingredient2', models.CharField(max_length=30)),
                ('ingredient3', models.CharField(max_length=30, null=True)),
                ('date_of_entry', models.DateTimeField()),
                ('title', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=30)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
