# Generated by Django 2.2.5 on 2020-09-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='date_of_entry',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient3',
        ),
        migrations.AddField(
            model_name='recipe',
            name='Directions',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Ingredients',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
