# Generated by Django 2.2.5 on 2020-11-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NflApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='height',
            field=models.PositiveIntegerField(max_length=3, verbose_name='Height (Inches)'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='position',
            field=models.CharField(choices=[('WR', 'WR'), ('LB', 'LB'), ('DL', 'DL'), ('RB', 'RB'), ('TE', 'TE'), ('OL', 'OL'), ('QB', 'QB'), ('DB', 'DB')], max_length=2),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='team',
            field=models.CharField(choices=[('Arizona Cardinals', 'Arizona Cardinals'), ('Dallas Cowboys', 'Dallas Cowboys'), ('Indianapolis Colts', 'Indianapolis Colts'), ('Detroit Lions', 'Detroit Lions'), ('Tennessee Titans', 'Tennessee Titans'), ('Pittsburgh Steelers', 'Pittsburgh Steelers'), ('Tampa Bay Buccaneers', 'Tampa Bay Buccaneers'), ('Atlanta Falcons', 'Atlanta Falcons'), ('Los Angeles Chargers', 'Los Angeles Chargers'), ('Carolina Panthers', 'Carolina Panthers'), ('Jacksonville Jaguars', 'Jacksonville Jaguars'), ('Los Angeles Rams', 'Los Angeles Rams'), ('New England Patriots', 'New England Patriots'), ('Philadelphia Eagles', 'Philadelphia Eagles'), ('Minnesota Vikings', 'Minnesota Vikings'), ('New Orleans Saints', 'New Orleans Saints'), ('Las Vegas Raiders', 'Las Vegas Raiders'), ('Buffalo Bills', 'Buffalo Bills'), ('Miami Dolphins', 'Miami Dolphins'), ('Denver Broncos', 'Denver Broncos'), ('San Francisco 49ers', 'San Francisco 49ers'), ('Washington Football Team', 'Washington Football Team'), ('New York Jets', 'New York Jets'), ('Kansas City Chiefs', 'Kansas City Chiefs'), ('New York Giants', 'New York Giants'), ('Cleveland Browns', 'Cleveland Browns'), ('Cincinnati Bengals', 'Cincinnati Bengals'), ('Seattle Seahawks', 'Seattle Seahawks'), ('Houston Texans', 'Houston Texans'), ('Baltimore Ravens', 'Baltimore Ravens'), ('Chicago Bears', 'Chicago Bears'), ('Green Bay Packers', 'Green Bay Packers')], max_length=30),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='weight',
            field=models.PositiveIntegerField(max_length=3, verbose_name='Weight (Pounds)'),
        ),
    ]
