# Generated by Django 2.2.5 on 2020-11-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NflApp', '0002_auto_20201106_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='height',
            field=models.PositiveIntegerField(verbose_name='Height (Inches)'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='position',
            field=models.CharField(choices=[('QB', 'QB'), ('RB', 'RB'), ('WR', 'WR'), ('DB', 'DB'), ('OL', 'OL'), ('LB', 'LB'), ('DL', 'DL'), ('TE', 'TE')], max_length=2),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='team',
            field=models.CharField(choices=[('Carolina Panthers', 'Carolina Panthers'), ('Indianapolis Colts', 'Indianapolis Colts'), ('New England Patriots', 'New England Patriots'), ('Green Bay Packers', 'Green Bay Packers'), ('Buffalo Bills', 'Buffalo Bills'), ('Washington Football Team', 'Washington Football Team'), ('Atlanta Falcons', 'Atlanta Falcons'), ('Los Angeles Chargers', 'Los Angeles Chargers'), ('Cleveland Browns', 'Cleveland Browns'), ('Jacksonville Jaguars', 'Jacksonville Jaguars'), ('Tampa Bay Buccaneers', 'Tampa Bay Buccaneers'), ('Detroit Lions', 'Detroit Lions'), ('Baltimore Ravens', 'Baltimore Ravens'), ('Miami Dolphins', 'Miami Dolphins'), ('Pittsburgh Steelers', 'Pittsburgh Steelers'), ('Arizona Cardinals', 'Arizona Cardinals'), ('Chicago Bears', 'Chicago Bears'), ('Seattle Seahawks', 'Seattle Seahawks'), ('Dallas Cowboys', 'Dallas Cowboys'), ('Las Vegas Raiders', 'Las Vegas Raiders'), ('Tennessee Titans', 'Tennessee Titans'), ('Denver Broncos', 'Denver Broncos'), ('Houston Texans', 'Houston Texans'), ('San Francisco 49ers', 'San Francisco 49ers'), ('Philadelphia Eagles', 'Philadelphia Eagles'), ('Minnesota Vikings', 'Minnesota Vikings'), ('New York Giants', 'New York Giants'), ('New York Jets', 'New York Jets'), ('Kansas City Chiefs', 'Kansas City Chiefs'), ('New Orleans Saints', 'New Orleans Saints'), ('Los Angeles Rams', 'Los Angeles Rams'), ('Cincinnati Bengals', 'Cincinnati Bengals')], max_length=30),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Weight (Pounds)'),
        ),
    ]
