# Generated by Django 2.2.5 on 2020-10-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acu_Insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acu',
            name='city_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='acu',
            name='clinic_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='acu',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='acu',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='acu',
            name='specialty',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='acu',
            name='street_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='acu',
            name='zip_code',
            field=models.CharField(default='', max_length=30),
        ),
    ]
