# Generated by Django 2.2.5 on 2020-10-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acu_Insurance', '0002_auto_20201016_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='copay',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='deductible',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='percent_covered',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
    ]
