# Generated by Django 2.2.5 on 2020-07-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(choices=[('Steven Brust', 'Steven Brust'), ('Brandon Sanderson', 'Brandon Sanderson'), ('Philip K Dick', 'Philip K Dick')], default='', max_length=80)),
                ('Title', models.CharField(default='', max_length=100)),
                ('Review', models.TextField(default='', max_length=1000, null=True)),
                ('Score', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
            ],
        ),
    ]
