# Generated by Django 2.2.5 on 2020-07-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFReview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='Author',
            field=models.CharField(choices=[('Brandon Sanderson', 'Brandon Sanderson'), ('Steven Brust', 'Steven Brust'), ('Philip K Dick', 'Philip K Dick')], default='', max_length=80),
        ),
    ]
