# Generated by Django 2.2.5 on 2020-07-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFReview', '0003_auto_20200706_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='Author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='Score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
