# Generated by Django 2.2.5 on 2020-07-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFReview', '0004_auto_20200706_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='Author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='Review',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
