# Generated by Django 2.2.5 on 2020-10-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigfootApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='enc_date',
            field=models.DateField(max_length=20, verbose_name='Encounter Date'),
        ),
    ]
