# Generated by Django 2.2.5 on 2020-09-29 23:07

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterFamiliarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mundane_name', models.CharField(max_length=50)),
                ('hero_or_villain', models.BooleanField(choices=[(True, 'Hero'), (False, 'Villain')], default=False)),
                ('affiliation', models.CharField(choices=[('Avengers', 'Avengers'), ('Inhumans', 'Inhumans'), ('X-Men', 'X-Men'), ('Defenders', 'Defenders'), ('Brotherhood of Mutants', 'Brotherhood of Mutants'), ('Other', 'Other')], default=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('sub_fname', models.CharField(max_length=50)),
                ('sub_lname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sub_email', models.EmailField(max_length=50)),
            ],
            managers=[
                ('Subscriber', django.db.models.manager.Manager()),
            ],
        ),
    ]
