# Generated by Django 2.2.5 on 2020-09-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelComicsApp', '0002_auto_20200930_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='sub_email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='sub_fname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='sub_lname',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='sub_username',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Username'),
        ),
    ]
