# Generated by Django 2.2.5 on 2020-10-01 16:03

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelComicsApp', '0003_auto_20200930_1021'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subscriber',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='sub_dob',
            field=models.DateField(default=django.utils.timezone.now, max_length=8, verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='sub_preference',
            field=models.BooleanField(default=True, verbose_name='Do you prefer to read comics online?'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='sub_username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Username'),
        ),
    ]
