# Generated by Django 2.2.5 on 2020-10-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelComicsApp', '0004_auto_20201001_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='sub_team',
            field=models.CharField(choices=[('Avengers', 'Avengers'), ('Inhumans', 'Inhumans'), ('X-Men', 'X-Men'), ('Fantastic 4', 'Fantastic 4'), ('Other', 'Other'), ('Guardians of the Galaxy', 'Guardians of the Galaxy')], default='', max_length=50, verbose_name='What is your favorite super team?'),
        ),
    ]
