# Generated by Django 2.2.5 on 2020-10-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelComicsApp', '0005_subscriber_sub_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='sub_dob',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='sub_preference',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='sub_team',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='sub_username',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Username'),
        ),
    ]
