# Generated by Django 2.2.5 on 2020-10-01 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelComicsApp', '0006_auto_20201001_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='sub_dob',
            field=models.DateField(default=django.utils.timezone.now, max_length=20, verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='sub_preference',
            field=models.BooleanField(default=True, verbose_name='Do you prefer to read comics online?'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='sub_team',
            field=models.CharField(choices=[('Guardians of the Galaxy', 'Guardians of the Galaxy'), ('Fantastic 4', 'Fantastic 4'), ('Inhumans', 'Inhumans'), ('Other', 'Other'), ('The Avengers', 'The Avengers'), ('The X-Men', 'The X-Men')], default='', max_length=50, verbose_name='What is your favorite super team?'),
        ),
    ]
