# Generated by Django 2.2.5 on 2020-10-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelComicsApp', '0007_auto_20201001_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='sub_team',
            field=models.CharField(choices=[('The Avengers', 'The Avengers'), ('Fantastic 4', 'Fantastic 4'), ('Guardians of the Galaxy', 'Guardians of the Galaxy'), ('Inhumans', 'Inhumans'), ('Other', 'Other'), ('The X-Men', 'The X-Men')], default='', max_length=50, verbose_name='What is your favorite super team?'),
        ),
    ]
