# Generated by Django 2.2.5 on 2020-10-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelComicsApp', '0009_auto_20201001_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
