# Generated by Django 2.2.5 on 2020-10-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelComicsApp', '0011_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='sub_username',
            field=models.CharField(default='', max_length=50, verbose_name='Username'),
        ),
    ]
