# Generated by Django 2.2.5 on 2020-10-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelComicsApp', '0012_auto_20201006_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='sub_username',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Username'),
        ),
    ]
