# Generated by Django 2.2.5 on 2020-10-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelComicsApp', '0013_auto_20201006_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='sub_preference',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=5, verbose_name='Do you prefer to read comics online?'),
        ),
    ]
