# Generated by Django 2.2.5 on 2020-09-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='game_title', max_length=100, unique=True, verbose_name='Game Title')),
                ('publisher', models.CharField(blank=True, db_column='publisher', max_length=50, null=True, verbose_name='Publisher')),
                ('ESRB_rating', models.CharField(blank=True, db_column='ESRB', max_length=20, null=True, verbose_name='ESRB Rating')),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Arcade', 'Arcade'), ('Board', 'Board'), ('Card', 'Card'), ('Casual', 'Casual'), ('Educational', 'Educational'), ('Fighting', 'Fighting'), ('Indie', 'Indie'), ('Massively-Multiplayer-Online', 'Massively-Multiplayer-Online'), ('Open-World-Game', 'Open-World-Game'), ('Platformer', 'Platformer'), ('Racing', 'Racing'), ('Role-Playing-Game', 'Role-Playing-Game'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Strategy', 'Strategy')], db_column='genre', max_length=30, null=True, verbose_name='Genre')),
                ('release_date', models.CharField(blank=True, db_column='release_date', max_length=20, null=True, verbose_name='Release Date')),
                ('user_rating', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_column='user_rating', null=True, verbose_name='User Rating')),
            ],
            options={
                'verbose_name': 'Game',
                'db_table': 'games_tbl',
            },
        ),
    ]
