# Generated by Django 2.2.5 on 2020-09-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NSW_App', '0005_auto_20200909_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Arcade', 'Arcade'), ('Board', 'Board'), ('Card', 'Card'), ('Casual', 'Casual'), ('Educational', 'Educational'), ('Fighting', 'Fighting'), ('Indie', 'Indie'), ('MMO', 'MMO'), ('Open World', 'Open World'), ('Platformer', 'Platformer'), ('Racing', 'Racing'), ('RPG', 'RPG'), ('Shooter', 'Shooter'), ('Sim', 'Sim'), ('Sports', 'Sports'), ('Strategy', 'Strategy')], db_column='genre', max_length=30, null=True, verbose_name='Genre'),
        ),
    ]
