# Generated by Django 2.2.5 on 2020-07-09 15:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('activity_level', models.CharField(max_length=50)),
                ('shedding', models.CharField(max_length=100)),
                ('hair_type', models.TextField(blank=True, default='', max_length=1000)),
                ('size', models.CharField(choices=[('under 10lbs', 'under 10lbs'), ('10lbs', '25lbs'), ('25lbs', '40lbs'), ('40lbs', '60lbs'), ('over 60lbs', 'over 60lbs')], max_length=100)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
