# Generated by Django 2.2.5 on 2020-07-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PupApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('XS', 'Tiny (under 10lbs)'), ('S', 'Small (10-20lbs)'), ('M', 'Medium (20-40lbs)'), ('L', 'Large (40-60lbs)'), ('XL', 'XLarge (over 60lbs)')], max_length=50)),
                ('play_type', models.CharField(choices=[('Gentle', 'Gentle'), ('Medium', 'Medium'), ('Rowdy', 'Rowdy')], max_length=50)),
                ('play_play', models.CharField(choices=[('Park', 'Park'), ('Water', 'Water')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='DogAttributes',
        ),
    ]
