# Generated by Django 2.2.5 on 2020-07-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PupApp', '0002_auto_20200709_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playtime',
            old_name='play_play',
            new_name='play_place',
        ),
    ]
