# Generated by Django 2.2.5 on 2020-07-10 21:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('PupApp', '0003_auto_20200709_1357'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='playtime',
            managers=[
                ('PlayTime', django.db.models.manager.Manager()),
            ],
        ),
    ]
