# Generated by Django 2.2.5 on 2020-07-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PupApp', '0004_auto_20200710_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='playtime',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
