# Generated by Django 2.2.5 on 2020-07-14 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PupApp', '0005_playtime_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_fname', models.CharField(max_length=50)),
                ('owner_lname', models.CharField(max_length=50)),
                ('owner_zipcode', models.CharField(max_length=10)),
                ('owner_phone', models.CharField(max_length=25)),
                ('owner_email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='playtime',
            name='owner',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='PupApp.Owner'),
            preserve_default=False,
        ),
    ]
