# Generated by Django 2.2.5 on 2020-07-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PupApp', '0006_auto_20200714_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_fname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_lname',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_phone',
            field=models.CharField(max_length=25, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_zipcode',
            field=models.CharField(max_length=10, verbose_name='Zip Code'),
        ),
    ]
