# Generated by Django 2.2.5 on 2020-07-14 21:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('PupApp', '0007_auto_20200714_1433'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='owner',
            managers=[
                ('Owner', django.db.models.manager.Manager()),
            ],
        ),
    ]
