# Generated by Django 2.2.5 on 2020-09-30 14:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=80, unique=True)),
                ('game_genre', models.CharField(blank=True, choices=[('RPG', 'RPG'), ('FPS', 'FPS'), ('MMO', 'MMO'), ('Adventure', 'Adventure'), ('Action', 'Action'), ('Simulation', 'Simulation'), ('Fighting', 'Fighting'), ('Platformer', 'Platformer'), ('Survival', 'Survival'), ('Indie', 'Indie'), ('Card', 'Card'), ('Stealth', 'Stealth'), ('Rhythm/Dance', 'Rhythm/Dance'), ('Text Adventure', 'Text Adventure'), ('Turn-Based', 'Turn-Based'), ('Strategy', 'Strategy'), ('Sports', 'Sports')], max_length=30, null=True)),
                ('game_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('game_publisher', models.CharField(max_length=30, null=True)),
                ('game_user_rating', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True)),
            ],
            managers=[
                ('Games', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50)),
            ],
            managers=[
                ('Profiles', django.db.models.manager.Manager()),
            ],
        ),
    ]
