# Generated by Django 2.2.5 on 2020-09-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_genre',
            field=models.CharField(blank=True, choices=[('RPG', 'RPG'), ('FPS', 'FPS'), ('MMO', 'MMO'), ('Adventure', 'Adventure'), ('Action', 'Action'), ('Simulation', 'Simulation'), ('Fighting', 'Fighting'), ('Text-Based', 'Text-Based'), ('Platformer', 'Platformer'), ('Survival', 'Survival'), ('Indie', 'Indie'), ('Card', 'Card'), ('Stealth', 'Stealth'), ('Rhythm/Dance', 'Rhythm/Dance'), ('Turn-Based', 'Turn-Based'), ('Strategy', 'Strategy'), ('Sports', 'Sports')], max_length=30, null=True),
        ),
    ]
