# Generated by Django 2.2.5 on 2020-10-01 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamesApp', '0002_auto_20200930_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
