# Generated by Django 2.2.5 on 2020-10-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesApp', '0004_auto_20201002_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_genre',
            field=models.CharField(choices=[('RPG', 'RPG'), ('FPS', 'FPS'), ('MMO', 'MMO'), ('Adventure', 'Adventure'), ('Action', 'Action'), ('Simulation', 'Simulation'), ('Fighting', 'Fighting'), ('Text-Based', 'Text-Based'), ('Platformer', 'Platformer'), ('Survival', 'Survival'), ('Indie', 'Indie'), ('Card', 'Card'), ('Stealth', 'Stealth'), ('Rhythm/Dance', 'Rhythm/Dance'), ('Turn-Based', 'Turn-Based'), ('Strategy', 'Strategy'), ('Sports', 'Sports')], default='', max_length=50, verbose_name='Favorite Game Genre?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
    ]
