# Generated by Django 2.2.5 on 2020-10-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesApp', '0006_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_genre',
            field=models.CharField(blank=True, choices=[('RPG', 'RPG'), ('FPS', 'FPS'), ('MMO', 'MMO'), ('Adventure', 'Adventure'), ('Action', 'Action'), ('Simulation', 'Simulation'), ('Fighting', 'Fighting'), ('Text-Based', 'Text-Based'), ('Platformer', 'Platformer'), ('Survival', 'Survival'), ('Indie', 'Indie'), ('Card', 'Card'), ('Stealth', 'Stealth'), ('Rhythm/Dance', 'Rhythm/Dance'), ('Turn-Based', 'Turn-Based'), ('Strategy', 'Strategy'), ('Sports', 'Sports')], max_length=30, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_publisher',
            field=models.CharField(max_length=30, null=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_title',
            field=models.CharField(max_length=80, unique=True, verbose_name='Game Title'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_user_rating',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='User Rating'),
        ),
    ]
