# Generated by Django 2.2.5 on 2020-11-02 02:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moon_name', models.CharField(max_length=50, verbose_name='Name')),
                ('moon_planet', models.CharField(max_length=50, verbose_name='Planet')),
                ('moon_diameter', models.IntegerField(blank=True, default='', null=True, verbose_name='Diameter')),
                ('moon_phase', models.CharField(max_length=50, verbose_name='Phase')),
                ('moon_phaseDeg', models.IntegerField(blank=True, default='', null=True, verbose_name='Phase Degree')),
                ('moon_orbit', models.IntegerField(blank=True, default='', null=True, verbose_name='Orbit Time')),
                ('moon_distance', models.IntegerField(blank=True, default='', null=True, verbose_name='Distance from Earth')),
                ('image', models.CharField(blank=True, default='', max_length=255)),
            ],
            managers=[
                ('moons', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(choices=[('Mercury', 'Mercury'), ('Venus', 'Venus'), ('Earth', 'Earth'), ('Mars', 'Mars'), ('Jupiter', 'Jupiter'), ('Saturn', 'Saturn'), ('Uranus', 'Uranus'), ('Neptune', 'Neptune')], max_length=50, verbose_name='Planet')),
                ('planet_freq', models.IntegerField(blank=True, default='', null=True, verbose_name='Musical Frequency')),
                ('planet_key', models.CharField(max_length=50, verbose_name='Musical Key')),
                ('planet_diameter', models.IntegerField(blank=True, default='', null=True, verbose_name='Diameter')),
                ('planet_mass', models.IntegerField(blank=True, default='', null=True, verbose_name='Mass')),
                ('planet_area', models.IntegerField(blank=True, default='', null=True, verbose_name='Area')),
                ('sun_distance', models.IntegerField(blank=True, default='', null=True, verbose_name='Distance from the Sun')),
                ('planet_orbit', models.IntegerField(blank=True, default='', null=True, verbose_name='Orbit Time')),
                ('escape_vel', models.IntegerField(blank=True, default='', null=True, verbose_name='Escape Velocity')),
                ('gravity', models.FloatField(blank=True, default='', null=True, verbose_name='Gravity')),
                ('atmosphere', models.CharField(max_length=50, verbose_name='Atmosphere')),
                ('image', models.CharField(blank=True, default='', max_length=255)),
            ],
            managers=[
                ('planets', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_name', models.CharField(max_length=50, verbose_name='Star Name')),
                ('star_type', models.CharField(max_length=50, verbose_name='Type')),
                ('atmosphere', models.CharField(max_length=50, verbose_name='Atmosphere')),
                ('star_temp', models.IntegerField(blank=True, default='', null=True, verbose_name='Star Temperature')),
                ('star_rotate', models.IntegerField(blank=True, default='', null=True, verbose_name='Revolution Time')),
                ('star_distance', models.IntegerField(blank=True, default='', null=True, verbose_name='Distance from Earth')),
                ('star_mass', models.IntegerField(blank=True, default='', null=True, verbose_name='Mass')),
                ('image', models.CharField(blank=True, default='', max_length=255)),
            ],
            managers=[
                ('stars', django.db.models.manager.Manager()),
            ],
        ),
    ]
