# Generated by Django 2.2.5 on 2020-11-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoundsOfSpace', '0002_auto_20201101_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moon',
            name='moon_distance',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='atmosphere',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='escape_vel',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='planet_freq',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='planet_key',
        ),
        migrations.RemoveField(
            model_name='star',
            name='star_rotate',
        ),
        migrations.AlterField(
            model_name='planet',
            name='planet_name',
            field=models.CharField(max_length=50, verbose_name='Planet'),
        ),
    ]
