# Generated by Django 2.2.5 on 2020-11-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoundsOfSpace', '0003_auto_20201102_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='gravity',
            field=models.FloatField(blank=True, default='0.00', null=True, verbose_name='Gravity'),
        ),
    ]
