# Generated by Django 2.2.5 on 2020-10-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60, verbose_name='Character Name')),
                ('alignment', models.CharField(choices=[('good', 'good'), ('evil', 'evil'), ('neutral', 'neutral')], max_length=10, verbose_name='Character Alignment')),
                ('catchPhrase', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Character Catch Phrase')),
                ('description', models.TextField(default='', max_length=300, verbose_name='Character Description')),
            ],
        ),
    ]
