# Generated by Django 2.2.5 on 2020-10-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RickAndMorty', '0002_auto_20201021_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='alignment',
            field=models.CharField(blank=True, choices=[('good', 'good'), ('evil', 'evil'), ('neutral', 'neutral')], max_length=10, null=True, verbose_name='Character Alignment'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300, null=True, verbose_name='Character Description'),
        ),
    ]
