# Generated by Django 2.2.5 on 2020-10-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RickAndMorty', '0004_auto_20201022_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Character Name'),
        ),
    ]
