# Generated by Django 2.2.5 on 2020-10-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RickAndMorty', '0006_auto_20201022_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='description',
            field=models.CharField(default='', max_length=450, verbose_name='Character Description'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='catchPhrase',
            field=models.CharField(default='', max_length=150, verbose_name='Character Catch Phrase'),
        ),
    ]
