# Generated by Django 2.2.5 on 2020-10-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RickAndMorty', '0007_auto_20201023_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='description',
            field=models.TextField(default='', max_length=450, verbose_name='Character Description'),
        ),
    ]
