# Generated by Django 2.2.5 on 2020-10-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RickAndMorty', '0008_auto_20201023_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='image',
            field=models.CharField(default='', max_length=300, verbose_name='Image URL'),
        ),
    ]
