# Generated by Django 2.2.5 on 2020-10-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RickAndMorty', '0009_auto_20201023_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='description',
            field=models.CharField(default='', max_length=450, verbose_name='Character Description'),
        ),
    ]
