# Generated by Django 2.2.5 on 2020-10-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RickAndMorty', '0010_auto_20201023_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='alignment',
            field=models.CharField(choices=[('Good', 'Good'), ('Evil', 'Evil'), ('Neutral', 'Neutral')], max_length=10, verbose_name='Character Alignment'),
        ),
    ]
