# Generated by Django 2.2.5 on 2020-09-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60, verbose_name='Restaurant Name')),
                ('cuisine', models.CharField(default='', max_length=60)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=None, null=True)),
                ('price', models.CharField(blank=True, choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$'), ('$$$$', '$$$$')], default=None, max_length=10, null=True)),
                ('address', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=60)),
                ('state_province', models.CharField(default='', max_length=60, verbose_name='State/Province')),
                ('zip_code', models.CharField(default='', max_length=60, verbose_name='Zip Code')),
                ('delivery', models.CharField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, max_length=10, null=True, verbose_name='Delivery?')),
                ('take_out', models.CharField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, max_length=10, null=True, verbose_name='Take-out?')),
                ('outdoor_seating', models.CharField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, max_length=10, null=True, verbose_name='Outdoor seating/area?')),
            ],
        ),
    ]
