# Generated by Django 2.2.5 on 2020-09-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0003_auto_20200919_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='highlights',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery',
            field=models.BooleanField(blank=True, null=True, verbose_name='Delivery'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='gluten_free',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gluten Free Options'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='takeaway',
            field=models.BooleanField(blank=True, null=True, verbose_name='Takeaway'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vegan',
            field=models.BooleanField(blank=True, null=True, verbose_name='Vegan Options'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vegetarian',
            field=models.BooleanField(blank=True, null=True, verbose_name='Vegetarian Options'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pricerange',
            field=models.IntegerField(blank=True, choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')], null=True, verbose_name='Price range'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Rating'),
        ),
    ]
