# Generated by Django 2.2.5 on 2020-09-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Single Family Home', 'Single Family Home'), ('Duplex', 'Duplex'), ('Condominium', 'Condominium'), ('Commercial', 'Commercial')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=30)),
                ('credit_hx', models.CharField(max_length=30)),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=1000000)),
            ],
        ),
    ]
