# Generated by Django 2.2.5 on 2020-09-25 16:15

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('Single Family Home', 'Single Family Home'), ('Duplex', 'Duplex'), ('Condominium', 'Condominium'), ('Commercial', 'Commercial')], default='', max_length=60)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.RemoveField(
            model_name='primarybank',
            name='credit_hx',
        ),
        migrations.RemoveField(
            model_name='primarybank',
            name='debt_amount',
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Renter', 'Renter'), ('Investor', 'Investor')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='client',
            name='credit_hx',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_bank',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RealEstateApp.PrimaryBank'),
            preserve_default=False,
        ),
    ]
