# Generated by Django 2.2.5 on 2020-09-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='natParksReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(choices=[('Arches National Park', 'Arches National Park'), ('Bryce National Park', 'Bryce National Park'), ('Glacier National Park', 'Glacier National Park'), ('Grand Canyon National Park', 'Grand Canyon National Park'), ('Grand Teton National Park', 'Grand Teton National Park'), ('Haleakala National Park', 'Haleakala National Park'), ('Rocky Mountains National Park', 'Rocky Mountains National Park'), ('Yellowstone National Park', 'Yellowstone National Park'), ('Yosemite National Park', 'Yosemite National Park'), ('Zion National Park', 'Zion National Park')], max_length=350)),
                ('date_arrived', models.DateField()),
                ('date_departed', models.DateField()),
                ('review_park', models.TextField()),
            ],
        ),
    ]
