# Generated by Django 2.2.5 on 2020-09-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NatParksApp', '0002_newsletterusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterUsers',
            new_name='NewsletterUser',
        ),
    ]
