# Generated by Django 2.2.5 on 2020-10-14 17:15

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(default=datetime.date.today, verbose_name="today's date")),
                ('first_name', models.CharField(max_length=50)),
                ('festival_title', models.CharField(max_length=200)),
                ('comment', models.CharField(blank=True, default='', max_length=1000)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
            managers=[
                ('reviews', django.db.models.manager.Manager()),
            ],
        ),
    ]
