# Generated by Django 2.2.5 on 2020-10-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FestivalApp', '0002_auto_20201014_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalreview',
            name='first_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=50, verbose_name='reviewers first name'),
        ),
    ]
