# Generated by Django 2.2.5 on 2020-10-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FestivalApp', '0003_auto_20201014_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalreview',
            name='first_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=50, verbose_name='reviewers name'),
        ),
    ]
