# Generated by Django 2.2.5 on 2020-10-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FestivalApp', '0007_uscities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uscities',
            name='lat',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='uscities',
            name='lng',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
    ]
