# Generated by Django 2.2.5 on 2020-10-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FestivalApp', '0008_auto_20201020_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uscities',
            name='lat',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='uscities',
            name='lng',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
    ]
