# Generated by Django 2.2.5 on 2020-10-21 02:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('FestivalApp', '0010_auto_20201020_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='USCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=70)),
                ('lat', models.DecimalField(decimal_places=20, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=20, max_digits=20)),
                ('country', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=50)),
            ],
            managers=[
                ('cities', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='US_Cities',
        ),
    ]
