# Generated by Django 2.2.5 on 2020-10-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FestivalApp', '0011_auto_20201020_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uscities',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uscities',
            name='lng',
            field=models.FloatField(),
        ),
    ]
