# Generated by Django 2.2.5 on 2020-10-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FestivalApp', '0012_auto_20201020_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='USCities',
            new_name='US_Cities',
        ),
    ]
