# Generated by Django 2.2.5 on 2020-09-05 20:48

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=75, unique=True)),
                ('password', models.CharField(max_length=75)),
            ],
            managers=[
                ('info', django.db.models.manager.Manager()),
            ],
        ),
    ]
