# Generated by Django 2.2.5 on 2020-09-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApproachApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('climbing_area', models.CharField(max_length=50)),
                ('climbing_wall', models.CharField(max_length=50)),
                ('climb_type', models.CharField(choices=[('T', 'Trad'), ('S', 'Sport'), ('B', 'Bouldering'), ('M', 'Mixed'), ('I', 'Ice')], max_length=15)),
                ('climb_grade', models.CharField(max_length=5)),
                ('climb_name', models.CharField(max_length=75)),
                ('sent', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApproachApp.ApproachUser')),
            ],
        ),
        migrations.CreateModel(
            name='Guidebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('publisher', models.CharField(max_length=100)),
                ('publishing_date', models.DateField()),
                ('climb_area', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TripManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=254, unique=True)),
                ('trip_description', models.TextField(max_length=500)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transportation', models.CharField(max_length=25)),
                ('shelter_type', models.CharField(max_length=50)),
                ('climbs', models.ManyToManyField(blank=True, to='ApproachApp.Climb')),
                ('people', models.ManyToManyField(to='ApproachApp.ApproachUser')),
            ],
        ),
    ]
