# Generated by Django 2.2.5 on 2020-09-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApproachApp', '0002_climb_guidebook_tripmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidebook',
            name='image',
            field=models.ImageField(blank=True, upload_to='./static/images/guidebook_img'),
        ),
    ]
