# Generated by Django 2.2.5 on 2020-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApproachApp', '0003_auto_20200909_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidebook',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
