# Generated by Django 2.2.5 on 2020-09-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApproachApp', '0005_auto_20200909_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidebook',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='images'),
        ),
    ]
