# Generated by Django 2.2.5 on 2020-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApproachApp', '0008_auto_20200909_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidebook',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/'),
        ),
    ]
