# Generated by Django 2.2.5 on 2020-09-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApproachApp', '0011_auto_20200909_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidebook',
            name='image',
        ),
    ]
