# Generated by Django 2.2.5 on 2020-09-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApproachApp', '0012_remove_guidebook_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebook',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/ApproachApp/'),
        ),
        migrations.AddField(
            model_name='tripmanager',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripmanager',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
