# Generated by Django 2.2.5 on 2020-09-10 11:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ApproachApp', '0013_auto_20200909_2339'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tripmanager',
            managers=[
                ('info', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='guidebook',
            name='image',
        ),
    ]
