# Generated by Django 2.2.5 on 2020-09-10 18:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ApproachApp', '0014_auto_20200910_0552'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='climb',
            managers=[
                ('view', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='guidebook',
            managers=[
                ('view', django.db.models.manager.Manager()),
            ],
        ),
    ]
