# Generated by Django 2.2.5 on 2020-09-11 21:06

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ApproachApp', '0015_auto_20200910_1101'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='climb',
            managers=[
                ('info', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='guidebook',
            managers=[
                ('info', django.db.models.manager.Manager()),
            ],
        ),
    ]
