# Generated by Django 2.2.5 on 2020-09-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savecities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities_name', models.CharField(max_length=75)),
                ('reason', models.CharField(max_length=200)),
                ('date_saved', models.DateField()),
                ('safety_rate_cities', models.DecimalField(decimal_places=4, default=0.0, max_digits=100)),
            ],
        ),
    ]
