# Generated by Django 2.2.5 on 2020-09-03 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RcanavApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savecities',
            old_name='safety_rate_cities',
            new_name='Rate_cities',
        ),
    ]
