# Generated by Django 2.2.5 on 2020-09-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RcanavApp', '0003_auto_20200903_1416'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='savecities',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='savecities',
            name='cities_name',
            field=models.CharField(choices=[('Bangui', 'Bangui'), ('Bouar', 'Bouar'), ('Boali', 'Boali'), ('Ouadda', 'Ouadda'), ('Baboua', 'Baboua')], max_length=75),
        ),
    ]
